# Generated by Django 5.1 on 2026-09-22 23:27

import django.db.models.deletion
import ussd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0004_alter_activespaceparticipant_id_alter_space_id_and_more'),
        ('wallet', '0008_alter_marzpaypayment_id_alter_smsbundle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSmsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_id', models.CharField(max_length=100, unique=True)),
                ('recipient_count', models.IntegerField()),
                ('credits_deducted', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_broadcast_records', to='spaces.space')),
                ('usage_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_broadcast_records', to='wallet.smsusagerecord')),
            ],
            options={
                'db_table': 'broadcast_sms_records',
            },
        ),
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(default='main_menu', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=ussd.models.default_session_expires_at, help_text='Sessions expire after 10 minutes of inactivity')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to='spaces.space')),
            ],
            options={
                'db_table': 'ussd_sessions',
                'indexes': [models.Index(fields=['phone_number'], name='ussd_sessio_phone_n_a4ce08_idx'), models.Index(fields=['state'], name='ussd_sessio_state_f300ff_idx'), models.Index(fields=['expires_at'], name='ussd_sessio_expires_466c9b_idx')],
            },
        ),
    ]
