# Generated by Django 6.0.2 on 2026-08-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_drop_subscription_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="sms_balance",
            field=models.PositiveIntegerField(
                default=0, help_text="Remaining SMS credit balance"
            ),
        ),
    ]
