# Generated by Django 6.0.2 on 2026-08-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_organization_sms_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="sms_balance",
            field=models.PositiveIntegerField(
                default=500, help_text="Remaining SMS credit balance"
            ),
        ),
    ]
