# Generated by Django 6.1 on 2026-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_organization_sms_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="sms_balance",
            field=models.PositiveIntegerField(
                default=0, help_text="Remaining SMS credit balance"
            ),
        ),
    ]
