# Generated by Django 5.1 on 2026-09-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_smsusagelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="smsusagelog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
