# Generated by Django 6.0.7 on 2026-07-18 09:20

import django.db.models.deletion
import spaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="space name", max_length=100)),
                ("host_phone", models.CharField()),
                (
                    "pin",
                    models.CharField(
                        default=spaces.models.generate_pin, max_length=4, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("name", "host_phone")},
            },
        ),
        migrations.CreateModel(
            name="ActiveSpaceParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "call_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_participants",
                        to="spaces.space",
                    ),
                ),
            ],
            options={
                "unique_together": {("space", "phone_number")},
            },
        ),
        migrations.CreateModel(
            name="SpaceInvitee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitees",
                        to="spaces.space",
                    ),
                ),
            ],
            options={
                "unique_together": {("space", "phone_number")},
            },
        ),
    ]
