# Generated by Django 6.0.2 on 2026-07-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="space",
        ),
        migrations.RemoveField(
            model_name="surveyquestion",
            name="survey",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="survey_question",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="user",
        ),
        migrations.DeleteModel(
            name="Broadcast",
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
        migrations.DeleteModel(
            name="SurveyQuestion",
        ),
        migrations.DeleteModel(
            name="SurveyResponse",
        ),
    ]
