# Generated by Django 5.1 on 2026-09-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0003_alter_activespaceparticipant_id_alter_space_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activespaceparticipant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="spacemember",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
