# Generated by Django 6.1 on 2026-08-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0004_alter_organization_sms_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("default_language", models.CharField(default="en", max_length=20)),
                ("sms_sender_id", models.CharField(blank=True, max_length=20)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=True)),
                ("voice_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="account.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization setting",
                "verbose_name_plural": "organization settings",
            },
        ),
    ]
