# Generated by Django 6.0.2 on 2026-08-04 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_credits",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of SMS credits available"
                    ),
                ),
                (
                    "cash_balance_ugx",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Remaining UGX cash that is insufficient for another credit",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="account.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmsUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broadcast_id", models.CharField(max_length=100, unique=True)),
                ("recipients_count", models.PositiveIntegerField()),
                ("credits_deducted", models.PositiveIntegerField()),
                ("status", models.CharField(default="sent", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("topup", "Top‑up"), ("deduction", "Deduction")],
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid_ugx",
                    models.PositiveIntegerField(
                        help_text="UGX amount paid by the organization"
                    ),
                ),
                (
                    "credits_added",
                    models.IntegerField(
                        help_text="SMS credits added (positive) or deducted (negative)"
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
    ]
