# Generated by Django 6.0.7 on 2026-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelecomNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. MTN Uganda, Airtel Uganda",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. MTN, AIRTEL, OTHER", max_length=20, unique=True
                    ),
                ),
                (
                    "provider_cost_ugx",
                    models.PositiveIntegerField(
                        help_text="Cost charged by Africa's Talking (e.g., MTN: 27, Airtel: 25, Other: 35)"
                    ),
                ),
                (
                    "markup_ugx",
                    models.PositiveIntegerField(
                        help_text="Fixed markup amount in UGX (e.g., MTN: 13, Airtel: 15, Other: 15)"
                    ),
                ),
                (
                    "selling_price_ugx",
                    models.PositiveIntegerField(
                        help_text="Selling price charged to customer in UGX (provider_cost_ugx + markup_ugx)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
