# Generated by Django 6.1 on 2026-08-25 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_marzpaypayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pesapalpayment",
            name="wallet_pesap_organiz_idx",
        ),
        migrations.RemoveIndex(
            model_name="pesapalpayment",
            name="wallet_pesap_order_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="pesapalpayment",
            name="wallet_pesap_tracking_idx",
        ),
        migrations.RenameIndex(
            model_name="marzpaypayment",
            new_name="wallet_marz_organiz_6f9c97_idx",
            old_name="wallet_marzp_organiz_idx",
        ),
        migrations.RenameIndex(
            model_name="marzpaypayment",
            new_name="wallet_marz_referen_0782f6_idx",
            old_name="wallet_marzp_reference_idx",
        ),
        migrations.RenameIndex(
            model_name="marzpaypayment",
            new_name="wallet_marz_transac_6ae5e5_idx",
            old_name="wallet_marzp_transac_idx",
        ),
        migrations.RenameIndex(
            model_name="smspurchase",
            new_name="wallet_smsp_organiz_86ac0b_idx",
            old_name="wallet_smspu_organiz_idx",
        ),
        migrations.RenameIndex(
            model_name="smspurchase",
            new_name="wallet_smsp_payment_882f19_idx",
            old_name="wallet_smspu_payment_idx",
        ),
        migrations.RenameIndex(
            model_name="smspurchase",
            new_name="wallet_smsp_pesapal_cc3d00_idx",
            old_name="wallet_smspu_pesapal_idx",
        ),
        migrations.AlterField(
            model_name="marzpaypayment",
            name="provider_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Telco network ID (e.g. MTN/Airtel ID)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marzpaypayment",
            name="reference",
            field=models.CharField(
                help_text="UUID v4 sent as request reference",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="marzpaypayment",
            name="transaction_uuid",
            field=models.CharField(
                blank=True,
                help_text="MarzPay system UUID",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="smspurchase",
            name="bundle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wallet.smsbundle",
            ),
        ),
        migrations.AlterField(
            model_name="smspurchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mobile_money", "Mobile Money"),
                    ("pesapal", "PesaPal"),
                    ("iotec", "ioTec"),
                    ("card", "Card"),
                    ("marzpay", "Marzpay"),
                ],
                default="pesapal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smspurchase",
            name="payment_reference",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="smspurchase",
            name="purchased_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="smspurchase",
            name="sms_count",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="PesapalPayment",
        ),
    ]
