# Generated by Django 6.1 on 2026-10-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_customuser_id_alter_member_id_and_more"),
        ("wallet", "0008_alter_marzpaypayment_id_alter_smsbundle_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="adjustment",
                        max_length=20,
                    ),
                ),
                (
                    "delta_credits",
                    models.IntegerField(
                        default=0, help_text="Signed change in available SMS credits"
                    ),
                ),
                (
                    "amount_ugx",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monetary value associated with the ledger entry",
                        max_digits=12,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("balance_before", models.IntegerField(default=0)),
                ("balance_after", models.IntegerField(default=0)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="marzpaypayment",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="smsusagerecord",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="smsusagerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("wallet", "idempotency_key"),
                name="sms_usage_unique_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("wallet", "idempotency_key"),
                name="wallet_transaction_unique_idempotency",
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_ledger_entries",
                to="account.organization",
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="wallet.wallettransaction",
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="usage_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="wallet.smsusagerecord",
            ),
        ),
        migrations.AddField(
            model_name="walletledgerentry",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="wallet.wallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="walletledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("wallet", "idempotency_key"),
                name="wallet_ledger_unique_idempotency",
            ),
        ),
    ]
