"""
Django settings for yo_space_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# pyrefly: ignore [missing-import]
from dotenv import load_dotenv
# pyrefly: ignore [missing-import]
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-6t)&zl1h448n%v8den8805uieb!^67$%3(jvgl6snrkzk8sl2n")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv("DEBUG", "True").lower() == "true"
DEBUG = True

ALLOWED_HOSTS = [
    "*",
    "yospacesug.com",
    "www.yospacesug.com",
]

# Africa's Talking Configuration
AT_VOICE_NUMBER = os.getenv("AFRICASTALKING_VOICE_NUMBER", "+256323200925")
AFRICASTALKING_USE_SANDBOX = os.getenv("AFRICASTALKING_USE_SANDBOX", "False").lower() == "true"
if AFRICASTALKING_USE_SANDBOX:
    AFRICASTALKING_LIVE_USERNAME = os.getenv("AFRICASTALKING_SANDBOX_USERNAME", "sandbox")
    AFRICASTALKING_LIVE_API_KEY = os.getenv("AFRICASTALKING_SANDBOX_API_KEY", "")
else:
    AFRICASTALKING_LIVE_USERNAME = os.getenv("AFRICASTALKING_USERNAME", "yo_space")
    AFRICASTALKING_LIVE_API_KEY = os.getenv("AFRICASTALKING_API_KEY", "atsk_d0ad900cfea42fa2fca26ee5bc47964c8e1e092d5565e4c0ce5217a82c5267ed079ab373")

AT_CONFERENCE_URL = "https://voice.africastalking.com/conference"
AT_CALL_URL = "https://voice.africastalking.com/call"

# MARZPAY_API_KEY = "marz_XSdy2ucLiJxdNkvx"
# MARZPAY_API_SECRET = "6iOsdoqTuJ9yzCKchuI6cTAdB8GwsRVp"
# MARZPAY_BASE64_AUTHORIZATION_HEADER = "bWFyel9YU2R5MnVjTGlKeGROa3Z4OjZpT3Nkb3FUdUo5eXpDS2NodUk2Y1RBZEI4R3dzUlZw" # ✨ Easiest option! This is your API Key and Secret already encoded.
# MARZPAY_COLLECT_URL = "https://wallet.wearemarz.com/api/v1/collect-money"

IOTEC_PAY_BASE_URL = os.getenv("IOTEC_PAY_BASE_URL", "https://pay.iotec.io")
IOTEC_IDENTITY_URL = os.getenv("IOTEC_IDENTITY_URL", "https://id.iotec.io")
IOTEC_PAY_ACCESS_TOKEN = os.getenv("IOTEC_PAY_ACCESS_TOKEN", "")
IOTEC_PAY_CLIENT_ID = os.getenv("IOTEC_PAY_CLIENT_ID", "")
IOTEC_PAY_CLIENT_SECRET = os.getenv("IOTEC_PAY_CLIENT_SECRET", "")
IOTEC_PAY_WALLET_ID = os.getenv("IOTEC_PAY_WALLET_ID", "")
IOTEC_PAY_TIMEOUT = int(os.getenv("IOTEC_PAY_TIMEOUT", "20"))


frontend_url = "https://yo-space-web.vercel.app/"
backend_url = "https://yo-space-2g.onrender.com/"
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise", 
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "account",
    "notifications",
    "poll", 
    "wallet",
    "spaces",
    "sms", "voice",
    "survey",
    "contact",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "yo_space_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

APPEND_SLASH = False
WSGI_APPLICATION = "yo_space_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# Database configuration.
# Production (Render) MUST use a persistent Postgres database via the DATABASE_URL
# environment variable. SQLite is ephemeral on Render's filesystem and is wiped on
# every restart/redeploy, which causes registered accounts to disappear and login
# to fail with "No active account found with the given credentials".
DATABASE_URL = os.getenv("DATABASE_URL") or os.getenv("POSTGRESQL_DB_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Local development fallback only.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
AUTH_USER_MODEL = "account.CustomUser"
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Argon2 is Django's recommended hasher: more resistant to GPU/ASIC attacks and
# typically faster than PBKDF2 at equivalent security, reducing login latency.
# PBKDF2 is kept as a fallback so existing hashed passwords still verify.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SMS_PRICE_OTHER_UGX = 60

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

# CORS & CSRF Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8000",
    "https://yo-space-web.vercel.app",
    "https://yo-space-2g.onrender.com",
    "https://yospacesug.com",
    "https://www.yospacesug.com",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
    r"^https://.*\.onrender\.com$",
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://*.vercel.app",
    "https://yo-space-web.vercel.app",
    "https://yo-space-2g.onrender.com",
    # "https://yospacesug.com",
    "https://yospacesug.com",
    "https://www.yospacesug.com",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]

# REST Framework & JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

